### PR TITLE
[WIP] Refactor Transform in amethyst_renderer

### PR DESCRIPTION
**Pull request by CBenoit**
I added the generic type N where required, but a lot of errors are remaining.

### CODE REVIEW

**Comment by topokel** [comment]
I feel like the `where` type clauses are a bit unnecessary when the `N` is going to be the only type parameter. You should be able to get the trait clause and an f32 default with the type parameter `<N: Real = f32>`. Traits may also be written `impl<N: Real>`

**Comment by CBenoit** [comment]
> I feel like the `where` type clauses are a bit unnecessary when the `N` is going to be the only type parameter. You should be able to get the trait clause and an f32 default with the type parameter `<N: Real = f32>`. Traits may also be written `impl<N: Real>`

Okay, I'll take that into account for future commits. :+1:

**Comment by AnneKitsune** [comment]
Should I merge this or it wasn't done?

**Comment by CBenoit** [comment]
I just force pushed my current modifications.
I didn't make f32 the default for N: Real at the moment since I'm a little bit afraid of the compiler not complaining if we forget to propagate the type parameter to other contained struct that requires it (might be okay since methods requiring N = f32 should end up being called with N = f64, but I'm not really sure of myself).
I still didn't figure out how to handle conversions cleanly and probably won't have time for it until Sunday or Monday. If you want to finish yourself or let someone else do it before, feel free to merge.

**Pull request merged**
